### ISSUE TITLE
Resultset not updated

### ISSUE THREAD

**Issue by tomvo** [arkverse/SwiftRecord#1]
I've implemented a pull to refresh which fetches data and syncs it to `CoreData` using Hyper `Sync` (https://github.com/hyperoslo/Sync/issues/103). However when I fetch the updated data again in the `onComplete` request it seems SwiftRecord does not return the new data.

Weirdest thing is when I do a normal CoreData fetch right after the `.all()` call, the data does get pulled in. I'm all new to this so not sure if I do something wrong but the behaviour seems odd.

Test:
```swift
        let friendsTest:[Friend] = Friend.all() as! [Friend]
        println("==================================")
        for friend in friendsTest {
            println(friend.name)
        }
```

Result:
```
==================================
Captain Willard
Lance Johnson
Colonel Walter E-Kurtz
==================================
```
*Expected result*

```
==================================
Captain Willard I'm Updated!!
Lance Johnson
Colonel Walter E-Kurtz
==================================
```

When I do the following:

```swift
let friendsTest:[Friend] = Friend.all() as! [Friend]
        println("==================================")
        for friend in friendsTest {
            println(friend.name)
        }
        println("==================================")

        let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
        let managedContext = dataStack.mainContext
        let fetchRequest = NSFetchRequest(entityName:"Friend")
        var error: NSError?
        let fetchedResults = managedContext.executeFetchRequest(fetchRequest, error: &error) as? [Friend]
        
        if let results = fetchedResults {
            self.friends = results
        } else {
            println("Could not fetch \(error), \(error!.userInfo)")
        }

        self.tableView.reloadData()
        
        for friend in self.friends {
            println(friend.name)
        }

```

The result is two times the correct data:

```
==================================
Captain Willard I'm Updated!!
Lance Johnson
Colonel Walter E-Kurtz
==================================
Captain Willard I'm Updated!!
Lance Johnson
Colonel Walter E-Kurtz
==================================
```

So it seems my vanilla CoreData does something to the SwiftRecord data.

Any clue of what might be going on?

**Comment by zaiddag** [comment]
Hey @tomvo 

I can assure that this isn't an issue with SwiftRecord. `Friend.all()` calls the same code as your manual query. It may be a threading issue, as Sync runs multiple `NSManagedObjectContext`s in separate threads and merges them. It could be the merge hadn't completed yet in the first example.

Could you provide me with your full view controller so I can take a look and see if there's a timing issue there?

**Comment by tomvo** [comment]
@zaiddag Thanks for your response! However in the meantime I've switched to Realm so I'm sorry but cannot provide you anymore info. I reckon it must've been something with the merging I guess.
I had an API class that did an async call to fetch the data and in a callback updated the tableview.
