### ISSUE TITLE
Why core data storage space is not released？

### ISSUE THREAD

**Issue by daiKratos** [arkverse/SwiftRecord#12]
I create some data then delete them all
and I check out the usage in settings
storage space is not released

**Comment by zaiddag** [comment]
The database never gets deleted. If you want to delete the database, you would have to do it manually. You can get the URL by doing:
`SwiftRecord.sharedRecord.sqliteStoreURL`
Use it with `NSFileManager.defaultFileManager().removeItemAtPath`
