### ISSUE TITLE
Creating new record not handling <null> values

### ISSUE THREAD

**Issue by Struki84** [arkverse/SwiftRecord#14]
if I try to pass a dict object `[String: AnyObject]`

```
{
    email = "struki84gmail.com";
    id = 25;
    password = qwert;
    "recover_code" = "<null>";
    "registered_on" = "<null>";
    token = "<null>";
}
```

Create method returns something like 
```Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for attribute: property = "recoverCode"; desired type = NSString; given type = NSNull; value = <null>.'```

Create is not handling nulls in properties, thus making `create(properties)` pritty usless, since I have to manually check and update every filed.

**Comment by zaiddag** [comment]
Hmm, it seems Swift CoreData doesn't like null's, did you make your properties optional in your CoreData model, ie:
```
class User : NSManagedObject {
   @objc var recover_code:String?
```
also, you can set the default value of your properties in your core data model

**Comment by Struki84** [comment]
Tnx for the info, will look into it, and send some feedback, atm i did a small extension of nsmanagedobject:
```
public static func clean(data: [String:AnyObject]) -> [String:AnyObject] {
        var properties = data
        for (key, value) in properties {
            if let _ = value as? NSNull {
                properties.removeValueForKey(key)
            }
        }
        return properties
    }
```
Ugly hack but it works :)
