### ISSUE TITLE
Delete Object

### ISSUE THREAD

**Issue by juanm4** [arkverse/SwiftRecord#16]
I have created an Entity called User:

import Foundation
import CoreData
import SwiftRecord
@objc(User)
class User: NSManagedObject {
    @NSManaged var createdAt: NSDate?
    @NSManaged var password: String?
    @NSManaged var username: String?
}

When I want to get:
var user = User.find("username == %@", args: "username") as! User;
When I execute user.delete() and restart de aplication, I realize that the object "user" hasn't been removed from core data...¿Am I doing something wrong?

**Comment by zaiddag** [comment]
What version of SwiftRecord are you using?

**Comment by juanm4** [comment]
I am using 0.0.5.
Later, I have realized that if later of call to delete() function I call to save() function the object is removed correctly from core data.
The proccess will be:
user.delete()
user.save() //Here is the confirmation to remove object

It seems that the behavior of save() function is like a commit object, but I don't know if that is the correct behavior.

**Comment by zaiddag** [comment]
This is how Core Data is designed. All the core data changes you make are only done in memory. Once you save() the changes, SQLite is updated.

SwiftRecord calls save() in applicationWillTerminate() to save all your core data changes before the application dies, but if your application crashes or exits without calling willTerminate, the data won't be saved to SQLite

**Comment by Frexas** [comment]
delete() -> Ambiguous use of 'delete()' in xcode 7.3 swift 2.2
