### ISSUE TITLE
Member not defined

### ISSUE THREAD

**Issue by alex-taffe** [arkverse/SwiftRecord#2]
MYCLASS.Type does not have a member named create appears when trying to create in Xcode 6.3.2

**Comment by alex-taffe** [comment]
From the example project

![screen shot 2015-05-20 at 7 41 54 pm](https://cloud.githubusercontent.com/assets/6820226/7738941/4acf2d14-ff28-11e4-9afe-0a28bc102ed1.PNG)

**Comment by alex-taffe** [comment]
The issue appears not to occur when manually integrating with the .swift file, but the framework does have the issue

**Comment by zaiddag** [comment]
Yes, the .framework isn't copied into the example. I'll fix that right now.
