### ISSUE TITLE
Small fix for Swift2.3

### ISSUE THREAD

**Issue by glancashire** [arkverse/SwiftRecord#20]
First once more thanks for your work

Please declare the functions as optional

public func applicationSupportDirectory() -> NSURL? {
public var sqliteStoreURL: NSURL? {

**Comment by zarochintsev** [comment]
Hi, see my [pull request](https://github.com/arkverse/SwiftRecord/pull/21)

**Comment by glancashire** [comment]
Great, Thanks

Kind Regards

Graham

**Comment by r-a-o** [comment]
Can somebody please merge this PR? 

Unable to run my app on Xcode 8 even in Legacy mode as this pod breaks on Swift 2.3

**Comment by zaiddag** [comment]
Will pub new pod with PR
