### ISSUE TITLE
Compatibility with Swift 3

### ISSUE THREAD

**Issue by juanm4** [arkverse/SwiftRecord#24]
Hi, I have updated my projecto to Swift 3 and I have arround 80+ error in compilation time.

Is this library compatible with swift 3?

Thanks!

**Comment by jrafaelm** [comment]
It is not actually released, but you can refer to the github repo like this in your podfile:
    pod 'SwiftRecord', :git => 'https://github.com/arkverse/SwiftRecord.git';

But I'm actually getting ambiguous definition of Query and Find methods... I'll try to help the guys to solve these problems...
