### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by glancashire** [arkverse/SwiftRecord#26]
First thanks for your very nice library.

I have one question two weeks ago your library worked very nicely with Swift 3.0. Then about 12 days ago you merged a request from r-a-o, which turned back the wheel to Swift 2.3. Is there any reason for this? How can I go back to the Swift 3.0 version?

Kind Regards
Graham

**Comment by zaiddag** [comment]
Sorry, pushed fix. Use 0.0.6

**Comment by glancashire** [comment]
Thank you very much! If you are in the Region of Basel, I'll gladly buy you a coffee or beer ;-)
Graham
