### ISSUE TITLE
[NSKnownKeysDictionary1 _fastCStringContents:] iOS9

### ISSUE THREAD

**Issue by gali8** [arkverse/SwiftRecord#7]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSKnownKeysDictionary1 _fastCStringContents:]: unrecognized selector sent to instance 0x18a8de10'

during properties[entity.propertiesByName] in the  public static func keyForRemoteKey(remote: String, context: NSManagedObjectContext) -> String function

Only in iOS9!

**Comment by zaiddag** [comment]
Should be fixed in 0.0.4, let me know
